const mockBag = [{
  id: 0,
  title: 'Algodão Pima',
  category_name: 'Jérsei',
  url_image: 'https://i.imgur.com/dDldc4q.png',
  price: 71.25,
  oldPrice: 75.00,
  color_name: 'Azul',
  color: '#74bcf7',
  size: 'M',
  quantity: 2,
  discount: 5,
  identifyBag: '0#74bcf7M',
  product_option: 1,
  code: '3SFA469',
}, {
  id: 1,
  title: 'Secrect state',
  category_name: 'Terno',
  url_image: 'https://i.imgur.com/aEmfC0g.png',
  price: 150.00,
  oldPrice: 150.00,
  color_name: 'Azul meia noite',
  color: '#2a4f6c',
  size: 'P',
  quantity: 1,
  product_option: 2,
  discount: 0,
  identifyBag: '1#2a4f6cP',
  code: 'XTFA469',
}, {
  id: 2,
  title: 'Next station',
  category_name: 'Jaqueta',
  url_image: 'https://i.imgur.com/aEmfC0g.png',
  price: 33.12,
  color_name: 'Jeans Claro',
  color: '#8297af',
  size: 'G',
  oldPrice: 36,
  product_option: 3,
  quantity: 1,
  discount: 8,
  identifyBag: '2#8297afG',
  code: 'XT7A4D9',
}];

export default mockBag;
