const mockCards = [{
  id: 0,
  title: 'Nike F.C',
  type: 'Futebol',
  keyDesc: 'Nike Futebol',
  price: 'R$ 68,98',
  categoryId: 6,
  categoryName: 'Futebol',
  descrtion: '',
  branch: 'Nike',
  gender: 'Femenino',
  descount: 0,
  shipping: false,
  details: {
    mesh: 'Tactel + Algodão',
    model: 'Jaqueta',
    material: 'Algo',
    fabrictype: 'Nike',
    pokecket: '---',
    measures: '70*25*12',
    length: 'Medidas da peça: Ombro: 17cm Ombro a Ombro: 58cm Manga: 70cm Tórax: 128cm Comprimento: 79cm',
    available: true,
  },
  specification: {
    print: 'Silk',
    characteristics: 'Teste',
    wash: 'Pode se na maquina',
    occasion: 'Jogar Futebol',
  },
  options: [{
    colorName: 'Branco',
    color: '#fff',
    size: {
      P: 28,
      PP: 30,
      GG: 50,
      G: 40,
      M: 20,
    },
    img: ['url', 'url'],
  },
  {
    colorName: 'Cinza Escuro',
    color: '#333',
    size: {
      P: 28,
      PP: 30,
      GG: 50,
      G: 40,
      M: 20,
    },
    img: ['url', 'url'],
  },
  ],
},
{
  id: 1,
  title: 'Jérsei de Algodão Pima',
  type: 'Jérsei',
  keyDesc: '',
  price: 'R$ 150,90',
  categoryId: 5,
  categoryName: 'Casual',
  descrtion: '',
  branch: 'Lacoste',
  gender: 'Maculino',
  descount: 0,
  shipping: false,
  details: {
    mesh: 'Tactel + Algodão',
    model: 'Jaqueta',
    material: 'Algo',
    fabrictype: 'Lacoste',
    pokecket: '---',
    measures: '70*25*12',
    length: 'Medidas da peça: Ombro: 17cm Ombro a Ombro: 58cm Manga: 70cm Tórax: 128cm Comprimento: 79cm',
    available: true,
  },
  specification: {
    print: 'Tint',
    characteristics: 'Teste',
    wash: 'Pode se na maquina',
    occasion: 'Casual',
  },
  options: [{
    colorName: 'Branco',
    color: '#fff',
    size: {
      P: 28,
      PP: 30,
      GG: 50,
      G: 40,
      M: 20,
    },
    img: ['url', 'url'],
  },
  {
    colorName: 'Rosa',
    color: '#f8a3f8',
    size: {
      P: 0,
      PP: 30,
      GG: 0,
      G: 40,
      M: 20,
    },
    img: ['url', 'url'],
  },
  ],
}];

export default mockCards;
